### PR TITLE
rename to avoid conflict with travis-ci/travis

### PR DESCRIPTION
**Pull request by rkh**

### CODE REVIEW

**Comment by joshk** [comment]
@rkh trvs is taken by the tool used for common tasks we run on Pro, can you think of another one?

**Comment by sarahhodne** [comment]
How about just "travis-deploy"?

**Comment by rkh** [comment]
OK, trvs was @svenfuchs' suggestion in Campfire yesterday, we can sure rename it to anything.

**Comment by rkh** [comment]
"travis-deploy" might be slightly strange as it would then be "travis-deploy deploy".

**Comment by rkh** [comment]
Renamed to `travis-deploy`. Watcha think? I can't properly install the new client until we rename this :D.

**Comment by joshk** [comment]
sounds good to me for now :)

**Pull request merged**
