### PR TITLE
Ssl for encrypt

### PR DESCRIPTION
**Pull request by maxlinc**
Pretty much the same fix as evdb for issue #2 - but I added a test for the SecureKey fetch_key method using VCR.

You could use VCR's automatic re-recording or the idea of an "Integration Contract Test" to guard against regression.

### CODE REVIEW

**Comment by joshk** [comment]
Hey @maxlinc, this is great, one small thing is you might want to `require 'https'` instead of `http` in `secure_key.rb`

Once you have that changed I would be happy to merge this in.

@drogus would you be able to arrange releasing a new gem version?

**Comment by maxlinc** [comment]
I was curious to see if that would cause any matrix builds to fail.  The current documentation says: "In previous versions of ruby you would need to require ‘net/https’ to use HTTPS. This is no longer true."

I'd be happy to add it, but I don't think its necessary unless you want to support ruby 1.8.

**Comment by joshk** [comment]
@drogus Could you pretty please take care of this? (merge and release)

**Comment by drogus** [comment]
Sorry for delay and thanks for contribution. Since we had other RPs with this fix, I've merged #4, because it has best test coverage.

**Pull request closed without merging**
