### PR TITLE
Fixes fetching public keys over HTTPS

### PR DESCRIPTION
**Pull request by laserlemon**
The Travis API requires a connection over HTTPS but the `SecureKey` class is fetching over HTTP, so it's getting a redirect (301) rather than an OK (200) status. There were no tests surrounding `SecureKey` but there are now and they're green for all of the rubies in `.travis.yml` and a couple more. Although, I wasn't able to check jruby. Hope it helps! Thanks.

### CODE REVIEW

**Comment by laserlemon** [comment]
Just seeing now that there are other pull requests to this effect. Could we have one of them pulled in and a new version released? Thanks guys!

**Comment by laserlemon** [comment]
Hey guys, any word on this? Travis encryption is still broken until the fix is merged. Thank you!

**Comment by drogus** [comment]
@laserlemon sorry for delay, I was not getting notifications for this repo, but thankfully @roidrage pointed me to this :)

Thanks for your work, looks good to me. I'm just not sure why have you changed mocha to rspec mocking library? I'll merge it anyway, because I don't really care which one of those libraries we use and I can always get back to previous version, but I'm curious what's the gain here.

**Comment by laserlemon** [comment]
Thank you! No gain outside of the fact that Mocha was just an extra dependency since the test suite was already using RSpec. I imagine that when Mocha was added, it could do `any_instance` mocking and RSpec couldn't, but RSpec is up to speed now. Fewer dependencies == :+1:

Thanks again!

**Comment by drogus** [comment]
@laserlemon I've just pushed travis 0.0.7 to rubygems

/cc @evdb @maxlinc

**Pull request merged**
