### PR TITLE
Use https url to retrieve public key

### PR DESCRIPTION
**Pull request by evdb**
Hello,

When trying to encrypt an env I was getting the following error:

```
evdb@custard $ travis encrypt mysociety/popit foo=bar

About to encrypt 'foo=bar' for 'mysociety/popit'

There was an error while fetching public key, please check if you entered correct slug
```

Digging into the code and requesting the non-secure manually leads to a redirection to the secure url. `http://travis-ci.org/mysociety/popit.json` 301s to `https://travis-ci.org/mysociety/popit.json`

This pull request changes the url requested to be the secure one, and it now seems to work:

```
evdb@custard $ ./bin/travis encrypt mysociety/popit foo=bar

About to encrypt 'foo=bar' for 'mysociety/popit'

Please add the following to your .travis.yml file:

  secure: "H/WfWa7eoibxl/lGolJSKYETJGsMPWpgGF+vx0QogQiheNuyZYOxMl8rns5l\nbGPAiFxludAlaPWR+1t/tfWVunHuZMuysGlxdfLxJK+SDBPzD0hJNctT5TtC\naEikldU9U+DvppQESKeSwt1EuN+XMopIjjTQjy9K+eS2A8mGxDs="
```

Lovely lovely service. Thanks!

### CODE REVIEW

**Comment by larrycai** [comment]
@evdb : thx this is really useful for me, finally it works

**Comment by drogus** [comment]
Thanks for contribution, but since we had other RPs with this fix, I've merged #4, because it has best test coverage.

**Comment by evdb** [comment]
No problem - thanks for fixing the issue :)

**Comment by letmaik** [comment]
Hmm, is this working? I get `...http.rb:799:in 'connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)` I installed the travis gem and then manually changed the `secure_key.rb` file with the contents of [this commit](https://github.com/evdb/travis-cli/blob/4614d945195899e9537068ae805422a796e0e3ae/lib/travis/cli/secure_key.rb).
But when I try to fetch `https://travis-ci.org/neothemachine/glge-gwt.json` in a browser, I don't get a json back either. What am I doing wrong?

**Comment by drogus** [comment]
Which OS do you use? Is it ubuntu? Some of the distros need to have path to certificates set manually.

**Comment by letmaik** [comment]
I use Windows, and also if I add `http.verify_mode = OpenSSL::SSL::VERIFY_NONE` to the code to ignore certificates I get `There was an error while fetching public key, please check if you entered correct slug`

**Comment by drogus** [comment]
Could you also check what is the response and body in the place where the message that you pasted is printed? I guess we will need to add `--show-errors` option to allow stop escaping such things.

**Comment by letmaik** [comment]
Response code is 301.

Headers are:

```
age = 335
cache-control = public, must-revalidate
content-location = /
content-type = text/html
date = Mon, 12 Nov 2012 19:32:29 GMT
etag = 04e4b8da
expires = Tue, 12 Nov 2013 18:40:47 GMT
last-modified = Mon, 12 Nov 2012 18:40:47 GMT
location = https://api.travis-ci.org/neothemachine/glge-gwt.json
strict-transport-security = max-age=31536000
vary = Accept,Accept-Encoding
x-content-digest = 19d8b6dcfe4b51e0a0f78f0ca9ace38c004c636e
x-rack-cache = fresh
content-length = 671
connection = Close
```

Body is:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta rel="travis.api_endpoint" href="https://api.travis-ci.org">
    <meta name="travis.pusher_key" value="23ed642e81512118260e">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Travis CI - Free Hosted Continuous Integration Platform for the Open Source Community</title>
    <link rel="icon" type="image/png" href="/favicon.ico">
    <link rel="stylesheet" href="/04e4b8da/styles/app.css">
    <script src="/04e4b8da/scripts/app.js"></script>
    <script>
      minispade.require('travis')
      Travis.run()
    </script>
  </head>
  <body id="home"></body>
</html>
```

When I use `uri = URI.parse("https://api.travis-ci.org/#{slug}.json")` I get headers:

```
access-control-allow-credentials = true
access-control-allow-origin = *
access-control-expose-headers = Content-Type, Cache-Control, Expires, Etag, Last-Modified
content-type =
date = Mon, 12 Nov 2012 19:40:02 GMT
location = https://api.travis-ci.org/repositories/neothemachine/glge-gwt.json
status = 302 Found
strict-transport-security = max-age=31536000
vary = Accept-Encoding
x-cascade = pass
x-oauth-scopes =
x-rack-cache = miss
content-length = 0
connection = Close
```

And again the same error...

BUT when I finally use `uri = URI.parse("https://api.travis-ci.org/repositories/#{slug}.json")` AND `http.verify_mode = OpenSSL::SSL::VERIFY_NONE` I get my encrypted vars...

BTW: I just tried it on my local JVM base box with travis gem (without modifications) and it worked without problems.

**Comment by drogus** [comment]
It uses wrong url, are you at `0.0.8`? Could you try to run `gem update travis` and then check which version you have on `gem list`?

**Comment by letmaik** [comment]
I just installed it today, gem list says 0.0.8.

**Comment by letmaik** [comment]
Well, actually, I think I changed the url first time, the original URL in my 0.0.8 source was `uri = URI.parse("https://api.travis-ci.org/#{slug}.json")` Sorry for that. But this isn't working either as you saw. But in my browser it is.

**Comment by drogus** [comment]
The original host is `secure.travis-ci.org`, but that really does not matter. The error you're seeing is there because you don't have valid certificates file, could you give me your rubygems version? If that's possible, please try to upgrade rubygems.

**Comment by drogus** [comment]
According to [release notes](https://github.com/rubygems/rubygems/blob/1.8/History.txt), you want 1.8.24 release, which seems to be the newest one.

**Comment by letmaik** [comment]
Ok I had 1.8.23, updated it, and used the latest code from `https://github.com/travis-ci/travis-cli/blob/master/lib/travis/cli/secure_key.rb`. Now, it works, but ONLY if I add `http.verify_mode = OpenSSL::SSL::VERIFY_NONE`, otherwise I get the certificate error. So 1.8.24 made it a bit better, but not completely.

**Comment by drogus** [comment]
@neothemachine the update of rubygems should fix the issue with SSL verification, so it didn't do what I thought it will. I did some more digging and apparently on Windows you need to fix it by yourself, here are the instructions: https://gist.github.com/867550

**Comment by letmaik** [comment]
Hm ok, still a bit lame though. I thought of integrating a work-around especially for Windows users which ignores cert errors, but I guess this is too insecure for such sensitive information.

**Comment by drogus** [comment]
@neothemachine we will not use `VERIFY_NONE`, that's for sure. We could bundle cert file and use it for windows users, but I'm not a fan of such solution. This means that people will be not aware that the problem exists and will not push maintainers of windows ruby installers to fix it for all, not for one particular gem. Historically, people were using `VERIFY_NONE`  a lot, which hid the issue and then when finally someone wanted to do verification, they needed to learn why the thing does not work and how to fix it (or they simply returned to using `VERIFY_NONE`).

**Pull request closed without merging**
